### ISSUE TITLE
upgrade to PG 12/13

### ISSUE THREAD

**Issue by Impavidity** [constructive-io/pgsql-parser#21]
Hey thank you for your excellent library. I want to know how to use higher version of pg parser such as pg12?

**Comment by pyramation** [comment]
Thank you! Appreciate the kind words :) 

We're currently dependent on https://github.com/lfittl/libpg_query to upgrade to 12. Lucky for us, it's in the works here https://github.com/lfittl/libpg_query/tree/12-latest-develop

The only problem is that I did try it out, while I got it to somewhat "work" locally, it didn't work with npm install because the build tests fail (the C/C++ ones) causing the npm install process to fail. 

I will keep this issue up to date for when we do get a 12 version, and if I can hack something together, a 12 branch that could potentially work even if I get it to only work experimentally.

**Comment by pyramation** [comment]
were there specific commands you wanted to parse by chance @Impavidity ? Like generated columns? it is potentially possible that we simply update the deparser, and hack the tests to ignore the fact that the parser cannot parse them, and we can get ahead on a few features for when 12/13 comes

**Comment by pyramation** [comment]
anyone interested in upgrading to 12 please thumbs up the conversation here https://github.com/lfittl/libpg_query/pull/67. ;)

my attempts at upgrading to 12
https://github.com/pyramation/node-pg-query-native/commit/e9e2d035f59bd24044b5f220a682d162157504fa

**Comment by Impavidity** [comment]
I am going to use the RANGE + interval (RANGE BETWEEN '10 days' PRECEDING AND CURRENT ROW).

**Comment by pyramation** [comment]
Thanks @Impavidity can you provide a full, complete query/statement example I can use for testing?

**Comment by Impavidity** [comment]
sure. Here is one example
```
WITH timestamp_measurement AS (SELECT count(t1.id) AS count_num
                                    , date_trunc('month', t1.start_date) AS timestamp
                               FROM trip AS t1
                               GROUP BY timestamp)

  SELECT t2.timestamp AS timestamp
       , avg(t2.count_num) OVER (ORDER BY t2.timestamp ASC RANGE BETWEEN '3 months' PRECEDING AND CURRENT ROW) AS moving_count_num
  FROM timestamp_measurement AS t2
```

**Comment by ReinsBrain** [comment]
Hi @pyramation - so happy somebody is keeping this project moving forward. Regarding versions, given the dependence on libpg_query, would it be possible to support various versions of postgresql?

**Comment by pyramation** [comment]
@ReinsBrain thank you! Very passionate about ASTs and Postgres, it's the least I can do :)

yes! we're working to support PG 12/13 when this merges: https://github.com/lfittl/libpg_query/pull/87

**Comment by pyramation** [comment]
latest work for parser for PG 13 https://github.com/pyramation/node-pg-query-native/tree/13-latest-develop

**Comment by pyramation** [comment]
Just released the PG 13 port! Please test it out and let me know if you find anything. There are a few differences between the old and new parser, which are due to the major change, and also the libpg_query changes. 

Likely there are a few test cases still needed, I'm happy to add them as we add specific issues for each one. Currently I've implemented generated columns in the deparser as well as index include fields.
