### ISSUE TITLE
Deparser options

### ISSUE THREAD

**Issue by beeing** [constructive-io/pgsql-parser#38]
Hi @pyramation, do you think we can add in options to pass into deparser?

```
{
   beautify: false,
   semicolon: true
}
```

For `beautify` currently there are tabs and newlines in DDL statements and semicolon will be required when we run query in batch.

I just managed to convert from pg-query-native to pgsql-parser, however if the deparsed query without newline would help a lot.

Thanks in advance!

**Comment by pyramation** [comment]
Regarding tabs, would spaces work? For now, you can definitely use a JS regular expression to quickly remove those from any output. 

Regarding semicolon, there is a way to do this in the existing system. Using what I reverse engineered from testing, here is what I do, I wrap my AST with a `RawStmt` to control semi-colons. 

This will not return statement with semi-colon

```js
const stmt = { /* AST tree */ }
const ast = {
    RawStmt: {
        stmt
    }
};
```

This will return statement with semi-colon

```js
const stmt = { /* AST tree */ }
const ast = {
    RawStmt: {
        stmt_len: 1,
        stmt
    }
};
```

I'm also curious exactly, what is the issue with tabs, is it a cosmetic issue, and would you prefer to set the tab delimiter, or use 2 or 4 spaces instead?

For the semicolon, it's hard to decide the "proper" way to do this since the ASTs themselves already have a way, it may be best to use the reverse engineered spec via `RawStmt`. What are your thoughts? Perhaps this part just needs better documentation?

**Comment by beeing** [comment]
From your current deparse, I noticed there's newline and tabs (or spacing, not too sure its space or tab).

Since we are using the deparsed statement in server logs, this will create too many lines for the logs. And yes, I'm using regex replace currently.

I noticed that you add `;` when there's stmt_len too, perhaps this is fine for now as I didn't noticed any issues.

**Comment by pyramation** [comment]
@beeing I added options for newline and tab:

```
 pgsql-deparser@13.1.8
 pgsql-parser@13.1.8
```

You can probably just use a space for each one like this:

```
  const sql = deparse(tree, {
    newline: ' ',
    tab: '  '
  });
```

Please try it out and let me know how it works for you.

**Comment by beeing** [comment]
Works perfectly. Thanks @pyramation
